name: 'Deploy on netlify'

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - tst
      - prd

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v2
      - name: Using Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: Set NETLIFY_SITE_ID
        id: set_netlify_site_id
        run: |
          if [ "${{ github.ref }}" == "refs/heads/dev" ]; then
            echo "NETLIFY_SITE_ID=${{ secrets.DEV_NETLIFY_SITE_ID }}" >> $GITHUB_ENV
            ls -l
            npm run build:frontend
          elif [ "${{ github.ref }}" == "refs/heads/tst" ]; then
            echo "NETLIFY_SITE_ID=${{ secrets.TST_NETLIFY_SITE_ID }}" >> $GITHUB_ENV
          elif [ "${{ github.ref }}" == "refs/heads/prd" ]; then
            echo "NETLIFY_SITE_ID=${{ secrets.PRD_NETLIFY_SITE_ID }}" >> $GITHUB_ENV
          else
            echo "NETLIFY_SITE_ID=UNKNOWN_BRANCH" >> $GITHUB_ENV
          fi
      - name: Deploying on netlify
        uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: './frontend/build'
          functions_directory: 'netlify/functions/'
          comment-on-commit: true
